"""`aicommit config` — open the user config in $EDITOR, creating it on first run."""
from __future__ import annotations

import subprocess
import sys

from aicommit.config import user_config_path
from aicommit.ui import editor

DEFAULT_TEMPLATE = """\
# aicommit configuration. Generated by `aicommit config`.
#
# Per-repo overrides live in <repo>/.aicommit.toml.
# CLI flags and AICOMMIT_* env vars override everything below.

[llm]
backend     = "ollama"                  # ollama | llama-cpp
model       = "qwen2.5-coder:7b"
url         = "http://localhost:11434"
temperature = 0.1                       # lower = more deterministic, less hallucination
max_tokens  = 512

[commit]
style                = "conventional"           # conventional | plain
include_body         = true
validate             = false                    # auto-validate & correct on --validate
validate_max_retries = 2

[review]
enabled = false                         # run --review on every commit by default?

[changelog]
skip_conventional = true                # use the deterministic fast path when possible
"""


def run() -> int:
    path = user_config_path()
    created = False
    if not path.exists():
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(DEFAULT_TEMPLATE)
        except OSError as e:
            sys.stderr.write(f"error: could not create {path}: {e}\n")
            return 1
        created = True
        print(f"created {path}", file=sys.stderr)

    # Non-interactive context: don't launch an editor into a pipe; just print
    # the path so callers like `vi $(aicommit config)` and CI work cleanly.
    if not sys.stdout.isatty():
        print(path)
        return 0

    cmd = [*editor(), str(path)]
    try:
        rc = subprocess.run(cmd, check=False).returncode
    except FileNotFoundError:
        sys.stderr.write(
            f"error: editor not found ({cmd[0]!r}). "
            "Set $EDITOR (e.g. EDITOR=vim) or install nano.\n"
        )
        return 127
    # If we just created the file, don't surface the editor's rc — :cq from
    # vim or similar shouldn't undo the "I made you a config" win.
    return 0 if created else rc
